ci:
  autofix_prs: false
  autoupdate_schedule: "quarterly"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-symlinks
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: requirements-txt-fixer
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        types: [python]
        args: [-m=3, -tc]
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.2.2
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==19.10b0]
      args: [--nbqa-mutate]
    - id: nbqa-isort
      additional_dependencies: [isort==5.7.0]
      args: [--nbqa-mutate]
