language: python
group: travis_latest
dist: xenial
os: linux
sudo: false

git:
    submodules: false

env:
    global:
        - TOX_ARG=''

stages:
    - name: Generic tests

    - name: Cron tests
      if: type = cron

matrix:
    # Don't wait for allowed failures
    fast_finish: true
    include:
        - name: "3.7"
          env: TOX_ENV='py37'
          python: "3.7"
          stage: Generic tests

        - name: "3.7-plasmapydev"
          env: TOX_ENV='py37-plasmapydev'
          python: "3.7"
          stage: Generic tests

before_install:
        - git clone git://github.com/astropy/ci-helpers.git --depth 1
          # We do not want to create the test env
        - echo "" > ci-helpers/travis/setup_dependencies_common.sh
        - source ci-helpers/travis/setup_conda.sh
        - pip install tox

script:
  - tox -e $TOX_ENV $TOX_ARG
  - pip install --upgrade codecov
  - codecov

# Assess test coverage
after_success:
        - codecov
