[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "numpy"]

build-backend = 'setuptools.build_meta'

[ tool.gilesbot ]
  [ tool.gilesbot.pull_requests ]
    enabled = true

  [ tool.gilesbot.towncrier_changelog ]
      enabled = true
      changelog_skip_label = "No changelog entry needed"
      help_url = "https://github.com/PlasmaPy/PlasmaPy/blob/master/changelog/README.rst"
      changelog_missing = "Missing changelog entry"
      changelog_missing_long = "This pull request needs a changelog entry file in `changelog/NUMBER.TYPE.rst`. For more information, consult https://github.com/PlasmaPy/PlasmaPy/blob/master/changelog/README.rst "
      number_incorrect = "Incorrect changelog entry number (match PR!)"
      number_incorrect_long = "The changelog entry's number does not match this pull request's number."
      type_incorrect = "Incorrect changelog entry type (see list in changelog README)"
      type_incorrect_long = "The changelog entry for this PR must have one of the types (as in NUMBER.TYPE.rst) as described in the changelog README)."

[tool.isort]
line_length = 88
wrap_length = 80
sections = ["FUTURE", "STDLIB", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["plasmapy", ]
default_section = "STDLIB"
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
force_alphabetical_sort_within_sections = true
honor_noqa = true
lines_between_types = 1
