name: monthly tests

on:
  schedule:
  - cron: 17 7 2 * *
  workflow_dispatch:

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:

        - name: Python 3.8 with Astropy dev
          os: ubuntu-latest
          python: 3.8
          toxenv: py38-astropydev

        - name: Python 3.8 with matplotlib dev
          os: ubuntu-latest
          python: 3.8
          toxenv: py38-matplotlibdev

        - name: Python 3.8 with NumPy dev
          os: ubuntu-latest
          python: 3.8
          toxenv: py38-numpydev

        - name: Documentation with PlasmaPy dev
          os: windows-latest
          python: 3.8
          toxenv: build_docs-plasmapydev
          toxposargs: -q

        - name: Python 3.8 with xarray dev
          os: macos-latest
          python: 3.8
          toxenv: py38-xarraydev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox codecov
    - name: Install language-pack-fr and tzdata
      if: startsWith(matrix.name, 'Documentation')
      run: sudo apt-get install graphviz pandoc
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@v3.1.4
      with:
        file: ./coverage.xml
