name: CI

on:
  push:
    branches:
    - main
    - stable
    - v0.*.x
    tags:
    - v*
  pull_request:
  workflow_dispatch:

jobs:
  initial-tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

        - name: Python 3.10
          os: ubuntu-latest
          python: '3.10'
          toxenv: py310

        - name: Python 3.8 with minimal dependencies
          os: windows-latest
          python: 3.8
          toxenv: py38-all-minimal

        - name: Python 3.9, all tests, code coverage
          os: macos-latest
          python: 3.9
          toxenv: py39-all-cov

        - name: Linters
          os: ubuntu-latest
          python: 3.8
          toxenv: linters

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --progress-bar off --upgrade tox codecov
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@v3.1.2
      with:
        file: ./coverage.xml
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: python -m pip install --progress-bar off --upgrade tox
    - name: Install language-pack-fr and tzdata
      run: sudo apt-get install graphviz pandoc
    - name: Run tests
      run: tox  -e build_docs -- -q
