name: CI

on:
  push:
    branches:
      - master
      - v0.*.x
    tags:
      - "v*"
  pull_request:

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: Python 3.7
            os: ubuntu-latest
            python: 3.7
            toxenv: py37

          - name: Python 3.7 with Astropy dev
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-astropydev

          - name: Python 3.8 with code coverage
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-cov

          - name: Python 3.8 with Numpy dev
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-numpydev

          - name: Python 3.9 with PlasmaPy dev
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-plasmapydev

          - name: Python 3.9
            os: ubuntu-latest
            python: 3.9
            toxenv: py39

          - name: Python 3.8 (Windows)
            os: windows-latest
            python: 3.8
            toxenv: py38
            toxposargs: --durations=50

          - name: Python 3.8 (MacOS X)
            os: macos-latest
            python: 3.8
            toxenv: py38

          - name: Documentation
            os: ubuntu-latest
            python: 3.9
            toxenv: build_docs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install language-pack-fr and tzdata
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get install language-pack-fr tzdata
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox codecov
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    needs: tests
    steps:
    - uses: actions/checkout@master
    - name: Get history and tags for SCM versioning to work
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install requirements
      run: |
        pip install --upgrade pip
        pip install setuptools numpy wheel setuptools_scm
    - name: Build a binary wheel and a source tarball
      run: |
        python setup.py bdist_wheel
        python setup.py sdist
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_access_token }}
